#!/bin/sh

owd=`pwd`

PREFIX=@PREFIX@
if [ -d $PREFIX ]
then
    # When running from the install dir.
    labreaso=$PREFIX/libexec/labrea.so
    LABREA_INIT=$PREFIX/share/labrea-init.lua
else
    # When running from the src dir.
    cd `dirname $0`
    labreadir=`pwd -P`
    labreaso=$labreadir/labrea.so
    LABREA_INIT=$labreadir/init.lua
fi

cd $owd

usage() {
    echo "$@"
    echo "Usage:  $0 myscript.lua command [--arguments]"
    echo "For more info, see the wiki:  https://github.com/dustin/labrea/wiki"
    exit 1
}

case `uname -s` in
    Darwin)
        DYLD_FORCE_FLAT_NAMESPACE=YES
        DYLD_INSERT_LIBRARIES=$labreaso
        export DYLD_FORCE_FLAT_NAMESPACE
        export DYLD_INSERT_LIBRARIES
        ;;
    Linux)
        LD_PRELOAD=$labreaso
        export LD_PRELOAD
        ;;
    *)
        echo "Sorry, `uname -s` is not supported."
esac

LABREA_SCRIPT=$1
shift

if [ ! -f "$LABREA_SCRIPT" ]
then
    usage "Can't find labrea script."
fi

case $LABREA_SCRIPT in
    *.lua)
        ;;
    *.lc)
        ;;
    *.luc)
        ;;
    *)
        usage "'$LABREA_SCRIPT' doesn't look like a lua script."
esac

export LABREA_SCRIPT

if [ ! -f "$LABREA_INIT" ]
then
    echo "Can't find init file:  $LABREA_INIT"
    exit 1
fi
export LABREA_INIT

exec "$@"
