#!/bin/sh

owd=`pwd`
cd `dirname $0`
labreadir=`pwd -P`
labreaso=$labreadir/labrea.so
cd $owd

case `uname -s` in
    Darwin)
        DYLD_FORCE_FLAT_NAMESPACE=YES
        DYLD_INSERT_LIBRARIES=$labreaso
        export DYLD_FORCE_FLAT_NAMESPACE
        export DYLD_INSERT_LIBRARIES
        ;;
    Linux)
        LD_PRELOAD=$labreaso
        export LD_PRELOAD
        ;;
    *)
        echo "Sorry, `uname -s` is not supported."
esac

LABREA_SCRIPT=$1
shift

if [ ! -f "$LABREA_SCRIPT" ]
then
    echo "Can't find labrea script."
    exit 1
fi

case $LABREA_SCRIPT in
    *.lua)
        ;;
    *)
        echo "'$LABREA_SCRIPT' doesn't look like a lua script."
        exit 1
esac

export LABREA_SCRIPT

LABREA_INIT=$labreadir/init.lua
if [ ! -f "$LABREA_INIT" ]
then
    echo "Can't find init file:  $LABREA_INIT"
    exit 1
fi
export LABREA_INIT

exec "$@"
